version: 0.2

phases:
  build:
    commands:
      - ls -l # Logs root directory
      - chmod -R 777 *
  post_build:
    commands:
      - npm test

artifacts:
  files:
    - '**/*' # Sets all the files to be in the artifacts file
