version: 0.2

phases:
  build:
    commands:
      - ls -l # Logs root directory
      - chmod -R 777 *
      - zip -r commitment-form-processor.zip .

artifacts:
  files:
    - 'commitment-form-processor.zip' # Sets all the files to be in the artifacts file
    - 'JesusCaresAPI-prod-swagger-apigateway.yaml'
