version: 0.2

phases:
  install:
    commands:
      - pip install --upgrade awscli
  build:
    commands:
      - chmod -R 777 *
      - zip -r commitment-form-processor.zip .
      - aws cloudformation package --template-file commitment-form-processor.template --s3-bucket groundwire --s3-prefix commitment-form-processor --output-template-file commitment-form-processor-replaced.template
artifacts:
  files:
    - 'commitment-form-processor-replaced.template'
